require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/chassis", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Chassis. As you add validations to Chassis, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Chassis.create! valid_attributes
      get chassis_index_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      chassis = Chassis.create! valid_attributes
      get chassis_url(chassis)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_chassis_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      chassis = Chassis.create! valid_attributes
      get edit_chassis_url(chassis)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Chassis" do
        expect {
          post chassis_index_url, params: { chassis: valid_attributes }
        }.to change(Chassis, :count).by(1)
      end

      it "redirects to the created chassis" do
        post chassis_index_url, params: { chassis: valid_attributes }
        expect(response).to redirect_to(chassis_url(Chassis.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Chassis" do
        expect {
          post chassis_index_url, params: { chassis: invalid_attributes }
        }.to change(Chassis, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post chassis_index_url, params: { chassis: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chassis" do
        chassis = Chassis.create! valid_attributes
        patch chassis_url(chassis), params: { chassis: new_attributes }
        chassis.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the chassis" do
        chassis = Chassis.create! valid_attributes
        patch chassis_url(chassis), params: { chassis: new_attributes }
        chassis.reload
        expect(response).to redirect_to(chassis_url(chassis))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        chassis = Chassis.create! valid_attributes
        patch chassis_url(chassis), params: { chassis: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested chassis" do
      chassis = Chassis.create! valid_attributes
      expect {
        delete chassis_url(chassis)
      }.to change(Chassis, :count).by(-1)
    end

    it "redirects to the chassis list" do
      chassis = Chassis.create! valid_attributes
      delete chassis_url(chassis)
      expect(response).to redirect_to(chassis_index_url)
    end
  end
end
