default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: track_directory_development
  username: track_directory
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: track_directory_test
  username: track_directory
  password: track_directory
  host: localhost
  port: 5432

production:
  adapter: postgresql
  host: app-df972dc1-4bc2-4988-be0d-fbabd98266fe-do-user-14435925-0.b.db.ondigitalocean.com
  port: 25060
  username: kartcheckdb
  password: AVNS_YmCbtUYB8MYPF-I2JxN
  database: kartcheckdb
  sslmode: require
